language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

before_install:
- openssl aes-256-cbc -K $encrypted_cbbf36167afb_key -iv $encrypted_cbbf36167afb_iv
  -in application-aws.tar.enc -out application-aws.tar -d
- openssl aes-256-cbc -K $encrypted_5c967de37745_key -iv $encrypted_5c967de37745_iv
  -in application.tar.enc -out application.tar -d
- tar vxf application.tar
- tar vxf application-aws.tar

notifications:
  email:
    recipients:
      - cgc8016@ewhain.net