language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build -x test"
before_deploy:
- zip -r mail-cube-server *
- mkdir -p deploy
- mv mail-cube-server.zip deploy/mail-cube-server.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: mail-cube-storage
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  local_dir: deploy
  on:
    repo: JXS2021-CUBE/mail-cube-server
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_cbbf36167afb_key -iv $encrypted_cbbf36167afb_iv
  -in application-aws.tar.enc -out application-aws.tar -d
- openssl aes-256-cbc -K $encrypted_5c967de37745_key -iv $encrypted_5c967de37745_iv
  -in application.tar.enc -out application.tar -d
- tar vxf application.tar
- tar vxf application-aws.tar

notifications:
  email:
    recipients:
      - cgc8016@ewhain.net