logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
azure:
  storage:
    ConnectionString:
    container:
      name: mail-cube

spring:
  datasource:
    url: jdbc:mysql://jxs-2021.mysql.database.azure.com:3306/mail_cube?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&requireSSL=false
    username:
    password: 
  jpa:
    database-platform:
      org:
        hibernate:
          dialect:
            MySQL5InnoDBDialect
    show-sql: false